# Inline `build.lifecycle` commands can be defined
build:
  # lifecycle:
  # onInit:
  # - export VALUE=lol
  # - echo "much wow"
  # onGetCache:
  # - echo 'curl custom cache'
  # onPreBuild: # echo "$VALUE"
  # onBuild: |
  # echo 'Hello Netlify Build!'
  # npm run build:netlify
  publish: out

# Attach our plugins
plugins:
  - package: ./plugins/netlify-plugin-hello-world
    config:
      siteId: 428d7c08-b4c1-4eac-bf33-4be5aa107585 # $SITE_ID # 
      siteToken: e2344b6ac42f242412dec6e2b2f3a3878075d937f5a1b7323d82f22291332755 # $SITE_TOKEN # 
  # - package: netlify-plugin-image-optim
  # - package: "@netlify/plugin-sitemap"
  # config:
  # buildDir: out
  # baseUrl: https://naeluh.com
  # - config:
  # entryPoints:
  # - "out/**/*.html"
  # recursive: true
  # fontDisplay: swap
  # inlineCss: false
  # inlineFonts: false
  # package: netlify-plugin-subfont
